[package]
name = "bulk"
version = "0.4.8"
authors = ["Paul Colomiets"]
license = "MIT"
repository = "http://github.com/tailhook/bulk"
description = """
    A simple tool for making deb packages, repositories,
    and update version numbers.
"""

[dependencies]
tar = "0.4.7"
scan_dir = "0.3.2"
quire = "0.1.8"
argparse = "0.2"
rustc-serialize = "0.3"
flate2 = "0.2"
regex = "0.1.69"
lazy_static = "0.2.1"
unicase = "1.4.0"
log = "0.3.6"
env_logger = "0.3.3"
sha2 = "0.1.2"
time = "0.1.35"
matches = "0.1.2"
quick-error = "1.1.0"
git2 = { version="0.6.6", default-features=false }
tempfile = "2.1.6"

[[bin]]
name = "bulk"
path = "src/main.rs"
