[package]
name = "tin"
version = "0.1.0"
authors = ["Paul Colomiets"]

[dependencies]
tar = "0.3"
scan_dir = "0.3"
quire = "0.1"
argparse = "0.2"
rustc-serialize = "0.3"
shaman = "0.1"
flate2 = "0.2"

[[bin]]
name = "tin"
path = "src/main.rs"
