minimum-bulk: v0.3.0
metadata:
  name: bulk
  short-description: A package builder for multiple linux distributions
  long-description:
    A single tool for creating packages for multiple linux distributions. The
    tool favors simplicity over ubiquity and is intended for use for
    containers. So it lacks some rarely useful features like install scripts.
  version: $(git describe)
  architecture: $(dpkg --print-architecture)

repositories:

- kind: debian
  suite: static
  component: bulk
  keep-releases: 1
  match-version: ^\d+\.\d+\.\d+$

- kind: debian
  suite: static
  component: bulk-stable
  keep-releases: 1000
  match-version: ^\d+\.\d+\.\d+$

- kind: debian
  suite: static
  component: bulk-testing
  keep-releases: 100

versions:

- file: Cargo.toml
  block-start: ^\[package\]
  block-end: ^\[.*\]
  regex: ^version\s*=\s*"(\s*)"

- file: package.yaml
  regex: ^minimum-bulk:\s+v(\S+)
